<?php
/**
 * Created by PhpStorm.
 * User: dev
 * Date: 8/05/18
 * Time: 09:18 AM
 */
class Archer extends Unit{
    protected $damage = 20;
    public function attack(Unit $oponent){
        show("{$this->name} dispara una fleca a {$oponent->getName()}");
        $oponent->takeDamage($this->damage);
    }
    public function takeDamage($damage)
    {
        if (rand(0,1))
            parent::takeDamage($damage); // TODO: Change the autogenerated stub
    }
}
