<?php
/**
 * Created by PhpStorm.
 * User: dev
 * Date: 8/05/18
 * Time: 09:17 AM
 */
class Soldier extends Unit{
    protected $damage = 40;
    public function attack(Unit $oponent){
        show("{$this->name} corta a {$oponent->getName()} en dos");
        $oponent->takeDamage($this->damage);
    }
    public function takeDamage($damage)
    {
        parent::takeDamage($damage / 2); // TODO: Change the autogenerated stub
    }
}
